# Generated by Django 5.2.17 on 2026-09-11 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='room_type',
            field=models.CharField(choices=[('GENERAL', 'General'), ('SEMI_PRIVATE', 'Semi Private'), ('PRIVATE', 'Private'), ('ICU', 'ICU'), ('CONSULTATION', 'Consultation')], max_length=20),
        ),
    ]
