# Generated by Django 5.2.17 on 2026-09-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_receptionist_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='receptionist_id',
        ),
    ]
