# Generated by Django 5.2.17 on 2026-08-28 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lab_tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('normal_range', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('result_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lab_test', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='result', to='lab_tests.labtest')),
            ],
        ),
    ]
