# Generated by Django 5.2.17 on 2026-09-12 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0001_initial'),
        ('rooms', '0002_alter_room_room_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointment_room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='appointments', to='rooms.room'),
        ),
    ]
