# Generated by Django 5.2.17 on 2026-09-15 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientprofile',
            name='patient_id',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
