# Generated by Django 5.2.17 on 2026-09-11 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_doctorprofile_consultation_room'),
        ('rooms', '0002_alter_room_room_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorprofile',
            name='consultation_room',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_doctor', to='rooms.room'),
        ),
    ]
